### PR TITLE
feat: support for sharing dashboards

### PR DESCRIPTION
**Pull request by kurolz**
**What type of PR is this?**

/kind enhancement

**What this PR does / why we need it**:

We probably need to share the entire dashboard to other departments in the company, let them access anonymously.

**Which issue(s) this PR fixes**:

Fixes ccfos/nightingale#905

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kurolz** [comment]
image

image

**Comment by UlricQin** [comment]
@jsers  可以弄个列，列名就叫【公开】，根据public字段的值，展示成小滑块开关那种样式

**Comment by jsers** [comment]
@kurolz 发了一个新的 PR，优化了下代码，这个 PR 就新关了

**Comment by jsers** [comment]
https://github.com/n9e/fe-v5/pull/197

**Pull request closed without merging**
